### PR TITLE
Make README more friendly to new users

### PR DESCRIPTION
**Pull request by TAAPArthur**
Include an example section of how to use the api.
Better explain the pros of using this api (and when it shouldn't be
used).
Add a FAQ section and answer common questions.

### CODE REVIEW

**Comment by TAAPArthur** [comment]
@explosion-mental as per yer suggestion tried to include examples of how to use the lib and also expanded on why one would like to use it.

Created this as a PR in case you were interested in using this lib and had further questions and/or in general had suggestions.

**Comment by explosion-mental** [comment]
Thank you for the ping @TAAPArthur and yeah im interested, this makes things very '''easy'''. I would really like for this extra text to be added and maybe, consider putting the examples somewhere else?, for example: imlib2 has example programs in the same repository of their library.

I'm still trying to have a more simple ground to work on with `imlib2`, when I _finnish_ my 'alternative mode' thingy then I may consider switching (and learning) to this library. Hopefully someday I become a C wizard that can make a library (or wrapper) hehe.

**Comment by explosion-mental** [comment]
Some questions:

1. Since this is a wrapper this requires all the dependencies that it 'wraps' right?
2. It claims that it manages directories, does this means it '''verifies''' what files are truly images?
3. Following with the above, does that mean it loads them recursively? is there a way to load and be **one time** recursive? (e.g. what `find -maxdepth 1` does)

**Comment by TAAPArthur** [comment]
>     1. Since this is a wrapper this requires all the dependencies that it 'wraps' right?

It has to link against them so it requires them to be installed at build time for them to be used. As in if you are a system with none of depends, it will build but won't be able to load anything. And if you build with only Imlib2 installed, it will only support images that Imlib2 supports. It doesn't mean that every optional dependency is required to build the program

**Comment by TAAPArthur** [comment]
>     2. It claims that it manages directories, does this means it '''verifies''' what files are truly images?

It will try to load every file given to it and, in the case of directories every file it contains. If it can't load it, it is treated like an invalid image. In other words, files in a directory are treated the same as files passed explicitly. Most of the loaders can easily tell if something isn't in a format they recognize since they can just check the header (or in curl's case that the path is an url). Something to keep in mind is that by default the images are verified lazily by default. As in if you pass in a directory with 1000 text files, it will think you have 1000 images (which will be reported if you ask for the count) until it actually tries to load them. sxiv/nxsiv has the same behavior. There are options to auto-remove images that can't be loaded and the verifification that they can be loaded as soon as you add them.

To give an example with default settings if you start with ImageFileA, DirB (with 5 images files inside it) and NonAnImageFileC and open ImageFileA, it will report that there are 3 images. If you open DirB, the 5 images will be then be detected and 8 image files will be detected with DirB be NULL. With the `IMAGE_LOADER_REMOVE_INVALID` flag, DirB will be auto removed so 7 images will be reported and with this flag when NonAnImageFileC fails to open it will also be removed for a total of 6 images

**Comment by TAAPArthur** [comment]
>     3. Following with the above, does that mean it loads them recursively? is there a way to load and be **one time** recursive? (e.g. what `find -maxdepth 1` does)

There isn't an option to limit search depth (yet). I had considered it but wasn't convinced of the general it should be. There were 3 ways I was thinking of it.

1. One is to split the current directory loader into a recursive and non-recusrive where the latter ignoring directories. This would be complimented by a new feature to turn loaders on/off. So if one wanted to limit the depth to 1, they would just disable the recursive loader. And by default everything would be loaded recursively.

2. Another way is to special case directories and keep a counter for how deep one is. This would be a true `-maxdepth` but feel like it is overkill since a limit of None or 1 seem like the more common values. 

3. The last is a more generic notion of how many loaders it has already gone through. Like a regular image file would have cost 1, but a remote zip file would incur a cost of curl(1) and zip(1) for a total of 2. The same would be true for a zip file in directory or a file in a nested directory. In either case a maxdepth flag of 1 would exclude it. This seemed more general but way too powerful and more likely to be annoying than helpful.

Probably would end up implementing 1 unless a case is made for the need to arbitrarily limit depth

**Comment by explosion-mental** [comment]
I did the recursive thing by being recursive. A modified version of muennich `open_dir` (which I implemented to be for checking files and open the dir if it is one)

https://github.com/explosion-mental/mage/blob/bd825277480d92fc430ab38e4a9db2d2e7de5948/mage.c#L374

Maybe it can help.

**Comment by TAAPArthur** [comment]
>I did the recursive thing by being recursive. 

Recursive loading is already supported. I just didn't want to special case any specific loader as right now they are all more of less equal and/or reuse code.

>I would really like for this extra text to be added and maybe, consider putting the examples somewhere else?, for example: imlib2 has example programs in the same repository of their library.

Moved the examples to the new `tests/` directory. This way can also verify that the examples are still relevant and would grow to show off more features without crowding the README

**Comment by explosion-mental** [comment]
> > ```
> > 2. It claims that it manages directories, does this means it '''verifies''' what files are truly images?
> > ```
> 
> It will try to load every file given to it and, in the case of directories every file it contains. If it can't load it, it is treated like an invalid image. In other words, files in a directory are treated the same as files passed explicitly. Most of the loaders can easily tell if something isn't in a format they recognize since they can just check the header (or in curl's case that the path is an url). Something to keep in mind is that by default the images are verified lazily by default. As in if you pass in a directory with 1000 text files, it will think you have 1000 images (which will be reported if you ask for the count) until it actually tries to load them. sxiv/nxsiv has the same behavior. There are options to auto-remove images that can't be loaded and the verifification that they can be loaded as soon as you add them.
> 
> To give an example with default settings if you start with ImageFileA, DirB (with 5 images files inside it) and NonAnImageFileC and open ImageFileA, it will report that there are 3 images. If you open DirB, the 5 images will be then be detected and 8 image files will be detected with DirB be NULL. With the `IMAGE_LOADER_REMOVE_INVALID` flag, DirB will be auto removed so 7 images will be reported and with this flag when NonAnImageFileC fails to open it will also be removed for a total of 6 images

I don't really like that invalid files are "reported", imlib2 `imlib_load_image` isn't that noticeable if I used it as the function that checks whether the file is an image. Thinking back, maybe loading directories shouldn't on the lib but since this aims to be an `image viewer` library it is very convenient. I just git cloned `div`, you really like macros uh.

Edit: as a side note, do you use matrix?

**Comment by explosion-mental** [comment]
> > I did the recursive thing by being recursive.
> 
> Recursive loading is already supported. I just didn't want to special case any specific loader as right now they are all more of less equal and/or reuse code.
> 
> > I would really like for this extra text to be added and maybe, consider putting the examples somewhere else?, for example: imlib2 has example programs in the same repository of their library.
> 
> Moved the examples to the new `tests/` directory. This way can also verify that the examples are still relevant and would grow to show off more features without crowding the README

Don't mind me but, could you make an example as simple as a main function with a couple of variables?

**Comment by TAAPArthur** [comment]
>I don't really like that invalid files are "reported", imlib2 imlib_load_image isn't that noticeable if I used it as the function that checks whether the file is an image. 

I can see how that would be annoying. When scripting I pass in the exact images I wanted and when using it manually its either with a single image a single image or turns a Pictures directory that mainly contains pictures. I also use the `IMAGE_LOADER_REMOVE_INVALID` which hides this detail unless one looks at the count. I was thinking of adding a flag to "check" all the images, but such verification would just be loading all the image data. And in that case it is simple for the end user to do with a for loop. For example you could open/close all images and then all the remaining images will be valid. Of course proving this as a helper function also seems reasonable.

>Thinking back, maybe loading directories shouldn't on the lib but since this aims to be an image viewer library it is very convenient. 

The same problem would be present for invalid files (those that don't exist or aren't images), zips and remote urls. 

>I just git cloned div, you really like macros uh.

(I didn't think I used macros that much) I just get tired writing the same few lines over and over again. I hope I'm not over using macros.

>Don't mind me but, could you make an example as simple as a main function with a couple of variables?

There are tests [here](https://github.com/TAAPArthur/libimageloader/blob/master/tests/tests.c). The first few tests are standalone complete examples. The rest have some of the more mundane stuff (creating destroying context etc) in fixtures. Some of the commented examples include just opening an image and opening and image and removing all invalid images.

Do you mean a standalone example than can run on its own? Yeah I guess I don't have that. I didn't know what the use would be since the program just loads the image... guess I could dump the data out as a dummy program. Why not?

>Edit: as a side note, do you use matrix?

I don't. Don't have a strong objection just never had a reason to.

**Comment by explosion-mental** [comment]
> Do you mean a standalone example than can run on its own? Yeah I guess I don't have that. I didn't know what the use would be since the program just loads the image... guess I could dump the data out as a dummy program. Why not?

yeah it would help me understand better and I think this can expand to more people that are so used to the 'easy' imlib2 funcs.

> I don't. Don't have a strong objection just never had a reason to.

It's easier to talk there for me but #1 is also fine.

**Comment by TAAPArthur** [comment]
> yeah it would help me understand better and I think this can expand to more people that are so used to the 'easy' imlib2 funcs.

Created [example.c](https://github.com/TAAPArthur/libimageloader/blob/master/examples/example.c) which is a standalone program that just prints the raw image data

**Comment by explosion-mental** [comment]
> Created example.c which is a standalone program that just prints the raw image data

Yeah that is **really** nice thanks.

About the naming, what about `imgld`? or `ldimg`, etc
Suggestions for a better (clever) name should be on an issue, so let me think more.

**Comment by TAAPArthur** [comment]
Thanks for the feedback. I'm open to a better name

**Comment by explosion-mental** [comment]
hey @TAAPArthur, offtopic question.
I recall that u said u use sxiv on a phone (then its a linux phone?), anyway any thoughts on this https://github.com/explosion-mental/sacf ?

**Comment by TAAPArthur** [comment]
> hey @TAAPArthur, offtopic question. I recall that u said u use sxiv on a phone (then its a linux phone?), anyway any thoughts on this https://github.com/explosion-mental/sacf ?

Yeah I use the Pinephone. Sure I can take a look.

**Pull request merged**
