### PR TITLE
how to compile for dummies and little typo

### PR DESCRIPTION
**Pull request by explosion-mental**

### CODE REVIEW

**Comment by explosion-mental** [comment]
taking the oportunity to ask about changing a bit the style of the example as well, since I'm guessing it's where most people will take a look

**Comment by TAAPArthur** [comment]
2 thought.

First the `/**` vs `/*` is a stylistic choice not a type. I don't really care either way.

Second who is the target audience for this patch? Do they know that they have to adjust their library search patch and/or have already installed the library? It seems reasonable that someone who wouldn't know how to compile the example may just think they could checkout repro and run that command...

Instead there's a make target (`make examples/example`) to compile the example without making assumptions. Would steer people towards that instead.

**Comment by TAAPArthur** [comment]
2 thought.

First the `/**` vs `/*` is a stylistic choice not a type. I don't really care either way.

Second who is the target audience for this patch? Do they know that they have to adjust their library search patch and/or have already installed the library? It seems reasonable that someone who wouldn't know how to compile the example may just think they could checkout repro and run that command...

Instead there's a make target (`make examples/example`) to compile the example without making assumptions. Would steer people towards that instead.

**Comment by explosion-mental** [comment]
didn't notice the make target

**Pull request closed without merging**
